# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXrB7ZwzVquQpY8bA2Hzd9se6C0R4Ju_
"""

sistema = input("Deseja continuar com o sistema? (sim/não)  ").lower()

if sistema == "sim":
  print("Continuando...")
else:
  print("Encerrando...")

uf = input("Digite sigla do seu estado (ex: sp, rj): ").upper()

print(f"Estado cadastrado {uf}")

cupom_correto = "DESCONTO10"
cupom_digitado = input("Digite o seu cupom promocional: ").upper()

if cupom_digitado == cupom_correto:
  print("Cupom aplicado com sucesso!")
else:
  print("Cupom inválido.")

nome = input("Digite o seu primeiro nome: ").strip()

print(f"Nome limpo: '{nome}'")
print(f"Qualidade de caracteres: {len(nome)}")

usuario_correto = "aluno@escola.com"

login_digitado = input("Digite seu e-mail de login: ").stip().lower()

if login_digitado == login_digitado:
  print("loginreslizado!")
else:
  print("Falha no login")